package com.reconciliation.common.enums;

public enum ExceptionType {
    UNMATCHED_PAYMENT,
    UNMATCHED_REFUND,
    AMOUNT_MISMATCH,
    MISSING_CAPTURE,
    DUPLICATE_CAPTURE,
    SETTLEMENT_DISCREPANCY,
    ORPHAN_REFUND,
    STATUS_MISMATCH,
    FEE_DISCREPANCY,
    ORDER_AMOUNT_MISMATCH,
    MISSING_PAYMENT,
    UNREGISTERED_PAYMENT,
    PROVIDER_REPORT_MISMATCH,
    UNMATCHED_BANK_CREDIT,
    BANK_AMOUNT_MISMATCH,
    OVERDUE_BANK_CREDIT,
    OMS_ORDER_CANCELLED_WITH_PAYMENT
}
